<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "relax5core"
 *
 * Auto generated by Extension Builder 2018-05-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'relax5core',
    'description' => 'relax5core for typo3 7.x and up and PHP 7.x',
    'category' => 'plugin',
    'author' => 'Christoph Balogh',
    'author_email' => 'cb@lustige-informatik.at',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.2-rc80529',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];

/**
 * * 8.7.2-rc80529
 * cleanup of plugin wizard settings
 * 
 * 8.7.2-rc80524
 * corrected missing mapping for done in appointment model
 * 
 * 8.7.2-rc80513
 * added team and position to owner
 * added zoom and mapType to address
 * changed googleMapsApi script and corrected issues with geoOnly
 */